<a href="https://colab.research.google.com/github/jasonherz41/nba_Jason/blob/main/NBA_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
nba_df = pd.read_csv("https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/NBA%202024_25%20Data/nba_2024_25_player_stats.csv")

In [6]:
nba_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PLAYER_NAME           456 non-null    object
 1   TEAM_ABBREVIATION     456 non-null    object
 2   AGE                   456 non-null    float64
 3   GP                    456 non-null    int64
 4   MIN                   456 non-null    float64
 5   PTS                   456 non-null    float64
 6   REB                   456 non-null    float64
 7   AST                   456 non-null    float64
 8   STL                   456 non-null    float64
 9   BLK                   456 non-null    float64
 10  TOV                   456 non-null    float64
 11  FG_PCT                456 non-null    float64
 12  FG3_PCT               456 non-null    float64
 13  FT_PCT                456 non-null    float64
 14  PLUS_MINUS            456 non-null    float64
 15  PLAYER_HEIGHT_INCHES  456 non-null    int64
 16  PLAYER_WEIGHT         455 non-null    float64
 17  DRAFT_YEAR            456 non-null    object
 18  DRAFT_ROUND           455 non-null    object
 19  DRAFT_NUMBER          454 non-null    object
dtypes: float64(13), int64(2), object(5)
memory usage: 71.4+ KB

In [8]:
nba_df.isnull().sum()

PLAYER_NAME             0
TEAM_ABBREVIATION       0
AGE                     0
GP                      0
MIN                     0
PTS                     0
REB                     0
AST                     0
STL                     0
BLK                     0
TOV                     0
FG_PCT                  0
FG3_PCT                 0
FT_PCT                  0
PLUS_MINUS              0
PLAYER_HEIGHT_INCHES    0
PLAYER_WEIGHT           1
DRAFT_YEAR              0
DRAFT_ROUND             1
DRAFT_NUMBER            2
dtype: int64

In [24]:
nba_df.loc[nba_df["PLAYER_WEIGHT"].isnull()]
nba_df.loc[nba_df["PLAYER_NAME"] == "Jaylen Wells", "PLAYER_WEIGHT"] = 206.0
nba_df.loc[nba_df["PLAYER_NAME"] == "Jaylen Wells", ["PLAYER_NAME", "PLAYER_WEIGHT"]]

      PLAYER_NAME  PLAYER_WEIGHT
208  Jaylen Wells          206.0

In [29]:
nba_df.loc[nba_df["DRAFT_ROUND"].isnull()]
nba_df.loc[nba_df["DRAFT_NUMBER"].isnull()]
nba_df.loc[nba_df["PLAYER_NAME"] == "Haywood Highsmith", "DRAFT_ROUND"] = "Undrafted"
nba_df.loc[nba_df["PLAYER_NAME"] == "Haywood Highsmith", "DRAFT_NUMBER"] = "Undrafted"
nba_df.loc[nba_df["PLAYER_NAME"] == "T.J. McConnell", "DRAFT_ROUND"] = "Undrafted"
nba_df.loc[nba_df["PLAYER_NAME"] == "T.J. McConnell", "DRAFT_NUMBER"] = "Undrafted"

nba_df.loc[nba_df["PLAYER_NAME"].isin(["Haywood Highsmith", "T.J. McConnell"]),["PLAYER_NAME", "DRAFT_ROUND", "DRAFT_NUMBER"]]

           PLAYER_NAME DRAFT_ROUND DRAFT_NUMBER
158  Haywood Highsmith   Undrafted    Undrafted
404     T.J. McConnell   Undrafted    Undrafted